<?php
$title = 'Commissioner’s Statements';
$navComState = true;
include($_SERVER['DOCUMENT_ROOT'] . '/includes/head.php');
include($_SERVER['DOCUMENT_ROOT'] . '/includes/header.php');
include($_SERVER['DOCUMENT_ROOT'] . '/includes/navbar.php');
?>
<h1>Commissioner’s Statements</h1>
<div class="ExpandableSectionAccordion">
<div class="ExpandableSectionTitleContainer" id="ExpandableSection04">
        <p class="ExpandableSectionTitle">Statement of Commissioner Austin Cullen on the Impact of COVID-19</p>
        <p class="ExpandableSectionUnderTitleLeft"></p>
        <p class="ExpandableSectionUnderTitleRight">April 16, 2020</p>
    </div>
    <div class="ExpandableSection" id="ExpandableSectionContent04">
        <h2>Statement of Commissioner Austin Cullen<br />on the Impact of COVID-19</h2>
        <p>COVID-19, the insidious disease caused by the novel coronavirus, has caused unprecedented change in all of our lives. That change has occurred in a sudden and remarkable fashion as this deadly virus continues to besiege our world causing turmoil and grief. The virus, and the public health measures taken to slow its spread, have had an immense impact throughout the province of British Columbia.</p>
        <p>The purpose of this statement is to provide my update, as Commissioner, to the people of British Columbia about what COVID-19 means for the work of the Commission of Inquiry into Money Laundering.</p>
        <p>When this Commission was formed on May 15, 2019, money laundering was viewed as a serious threat to the social and economic well-being of British Columbians. Since that time, the Commission has undertaken significant steps towards fulfilling its mandate of casting light on the problem of money laundering in British Columbia and of examining the various ways in which it has been either combatted or enabled.</p>
        <p>Commission counsel have engaged with participants; interviewed many witnesses; engaged subject-matter experts to conduct research and analysis; sought the production of documents; and prepared for the hearings set to bring a broad array of information and evidence to the public’s attention. In the fall of 2019, we held public meetings in five locations around the province to hear directly from the people of British Columbia and earlier this year, we conducted initial public hearings during which the participants with standing gave opening submissions.</p>
        <p>Dealing with the issue of money laundering — which the people of British Columbia have told us is important — continues to be a priority. However, it is also crucial that we acknowledge that, at this moment in time, we place it in the context of the social, economic and physical upheavals brought by the devastating spread of the COVID-19 virus since early 2020. At this point it is impossible to predict when the effects of the COVID-19 virus will subside, and when our social, economic and physical health will return to a state of equilibrium. There is, however, no doubt that this will happen, and we will return to a more familiar state of affairs.</p>
        <p>In the meantime, the Commission continues with its work with such modifications and accommodations as are necessary to prioritize the health and safety of all involved, to comply with the recommendations of government and public health officials, and to be sensitive to the impact this virus is having on British Columbians. To that end, Commission lawyers and staff are working remotely from their homes. All contact with participants, lawyers, witnesses, experts, technicians and one another now takes place by telephone or videoconference. The Commission is in ongoing contact with those engaged with the Commission’s work, to ensure that their engagement does not put their health or well-being at risk.</p>
        <p>Understandably, some participants have been unable to fully carry on in the face of the current necessary restrictions, and other critical demands on their attention and time. The Commission will work to ensure that no one who has sought and been granted participant status will be compromised in their ability to engage with the Inquiry, and advance or guard their interests or rights. Similarly, the Commission will ensure that no steps will be taken that may imperil others’ rights or interests, unless and until that person or agency is able to engage with the Commission as a participant or otherwise. In short, the Commission is committed to ensuring that although its work will continue as much as possible through this unsettled and challenging period, no one will be prejudiced as a result.</p>
        <p>As matters currently stand, the hearings portion of the Inquiry is set in two blocks of time. The first is scheduled to start on May 25 and carry on until the end of June 2020. The second block of hearings will run from September 8 to December 18, 2020. We accept that it is not realistic or appropriate to conduct the initial May-June hearings with in-person attendance by witnesses, participants or their counsel or in a venue that is open to the public; those hearings will only proceed if we are able to conduct them remotely using videoconferencing technology able to link witnesses, participants, and Commission staff in a manner that sufficiently approximates a more conventional hearing and that provides access to the public. We are in the process of exploring options for proceeding with largely remote hearings. While our investigations of these technologies are ongoing, the initial indications are promising. It may also be necessary to modify the hours of sitting for the May-June hearing block to accommodate the needs of overseas witnesses (attending by video from abroad) and the childcare responsibilities of the participants and their lawyers as the hearings proceed.</p>
        <p>The primary focus of the May-June hearings will not be fact finding in relation to acts or omissions of individuals or agencies that may have contributed to money laundering in British Columbia. This hearing block will, instead, provide an introduction to and an exploration of larger issues of money laundering — such as a review of typologies of money laundering; its history and evolution; how it is perceived and dealt with in other jurisdictions; and the issue of quantification (attempts to measure the extent of money laundering activity).</p>
        <p>The Commission team is committed to moving forward in a responsible, safe and sensitive manner, always with a view to serving the public interest. We will continue to monitor developments and follow known health authority guidelines and to evaluate the propriety of our plans to conduct the initial May-June hearings remotely via video.</p>
        <p>Our hope and our plan are to continue with our work, to adapt to circumstances that have changed profoundly, and to make use of videoconferencing technology that makes possible today what would have been unachievable just a decade ago. As we move forward, we will provide updates on our plans and decisions through our website.</p>
        <p>My purpose in communicating with you at this time and in this way is to explain that although the Commission is continuing to fulfil its mandate through this very unsettled time, we are doing so in a manner that recognizes the overarching priority of the COVID-19 crisis and the need to fully support efforts to limit the spread of the virus. Our desire to proceed rests on the precept that in the fullness of time, the work we do now will benefit the social and economic well-being of the province.</p>
        <p style="text-align: right; margin-right: 40px">Austin Cullen, Commissioner</p>
    </div>
    <div class="ExpandableSectionTitleContainer" id="ExpandableSection02">
        <p class="ExpandableSectionTitle">Commissioner Austin Cullen Opening Remarks - Public Meetings</p>
        <p class="ExpandableSectionUnderTitleLeft"></p>
        <p class="ExpandableSectionUnderTitleRight">Oct/Nov 2019</p>
    </div>
    <div class="ExpandableSection" id="ExpandableSectionContent02">
        <h2>Commission of Inquiry into Money Laundering in British Columbia Public Meetings Commissioner Austin Cullen Opening Remarks</h2>
        <p>I would like to begin by welcoming you to this meeting and thanking you for attending. Your presence signals an interest in and a concern about the subject matter of this Inquiry. This event is part of a larger process, which will enable us to hear from various communities about the issues we are inquiring into.</p>
        <p>As you are aware, the Government of the Province of British Columbia established this Commission of Inquiry into Money Laundering in British Columbia on May 15, 2019. I have been appointed Commissioner.</p>
        <p>Present with me at this meeting—as I am sure you have noticed—are several members of the Commission team.</p>
        <p>Our Inquiry’s terms of reference are quite broad. Speaking generally, they require the Commission to study the prevalence of money laundering in, and its impact on, various economic sectors including gaming, horse racing, real estate, financial institutions and money service businesses, the corporate sector, luxury goods and professional services—including lawyers and accountants.</p>
        <p>The Commission is also mandated to review the acts and/or omissions of individuals and agencies responsible for combating money laundering, in order to determine whether those acts or omissions have contributed to the spread of money laundering and if so, whether they amount to corruption.</p>
        <p>In recent years, there has been extensive media investigation and coverage of money laundering. There have also been studies and reports prepared by academics and other experts that shed light on the prevalence of money laundering in the province and on its noticeable effects.</p>
        <p>As a result, the public has become aware of, and concerned about, this problem. One recent poll reported that approximately 90% of British Columbians are concerned about money laundering.</p>
        <p>It is part of this Inquiry’s role to add to the public’s understanding of the nature and scale of money laundering in the province and to address its concerns, to the extent possible, through recommendations for action.</p>
        <p>There is an incidental benefit from simply bringing additional concentrated attention to the crime of money laundering. The more awareness there is of its presence and of the profound social harms it propagates, the less complacency there can be for facilitating or tolerating it.</p>
        <p>Money laundering is a particularly insidious crime. Its roots are in offences that victimize others—often people who are vulnerable. In its actual commission, however, money laundering is akin to the transmission of a serious contagious disease. Both events may be inconspicuous, yet each invariably leads to an erosion of well-being.</p>
        <p>We will examine how money laundering is taking place in British Columbia. We will examine whether such transactions could be prevented with a better approach, better training, or a different legal or regulatory regime. We will look at whether lapses in judgment or honesty have compromised the prevention of money laundering and contributed to its growth. We will listen to proposed solutions to these problems and issues, and we will assess their effectiveness and compatibility with our constitutional imperatives. We will make recommendations to the government for their use.</p>
        <p>At this stage, the Commission is in the process of gathering information through the study of and follow-up on media reports; the review and analysis of other studies and reports; research into various legal and factual issues; the acquisition and review of documents held by agencies, individuals or corporate sources; and interviews of potential witnesses and experts. We are in a phase where much of the Commission’s work is happening out of the public spotlight, with lawyers, investigators and analysts drilling into the issues. All of this hard work will lead us to the evidence hearings, which will take place in 2020. We will make a point of providing detailed notice about all of this on our website as we carry on.</p>
        <p>Today’s public meeting and those we are holding around the province are part of that exploration and discovery process. We are not yet in a position to provide answers to questions. To attempt to do so would be premature and might amount to prejudging issues that have not been fully canvassed. We come to these meetings not to provide information, but to obtain it. Our responses to everything that we hear, see and read will be made at a later stage in the process: through an interim report to be issued in November of 2020 and a final report to be issued in May of 2021.</p>
        <p>It is our hope that these meetings will help raise awareness of the issues we are mandated to investigate, provide us with the nature and scale of public concern in different communities in the province, and help us to shape our approach and ultimate response to what has consistently been characterized as a serious problem requiring attention and action.</p>
        <p>I really appreciate that you have each taken the time to come here today to share your views about this problem. An engaged community is at the foundation of a well-functioning society. Your perspective and feedback about money laundering and how you feel that it is affecting your community is important to the work that we are doing at the Commission.</p>
        <p>I very much look forward to hearing from you.</p>
        <p>Thank you.</p>
    </div>
    <div class="ExpandableSectionTitleContainer" id="ExpandableSection03">
        <p class="ExpandableSectionTitle">Commissioner Cullen Speaking Notes Oral Hearing (Participants)</p>
        <p class="ExpandableSectionUnderTitleLeft"></p>
        <p class="ExpandableSectionUnderTitleRight">October 18, 2019</p>
    </div>
    <div class="ExpandableSection" id="ExpandableSectionContent03">
        <h2>Speaking Notes – Commissioner Austin Cullen<br>Commission of Inquiry into Money Laundering in British Columbia</h2>
        <p>Before I formally open this hearing, I would like to say a few words since this is the first time that I am speaking publicly in my role as Commissioner of the Commission of Inquiry into Money Laundering in British Columbia.</p>
        <p>This hearing has been convened in accordance with a direction I made following the receipt of 20 applications from various individuals and entities seeking leave to participate in the Commission of Inquiry into Money Laundering in British Columbia. On September 24, 2019, I granted participant status to 16 of the applicants with a direction that the remaining four applicants—Messrs. Alderson, Desmarais, Lightbody and Pinnock—attend an oral hearing of the Inquiry to enable a further review and determination of their individual circumstances in light of the relevant considerations governing those applications.</p>
        <p>In the meantime, the British Columbia Real Estate Association sought—and was granted—an extension of time to apply for participant status. I granted the extension of time and their application for participant status on October 16, 2019. My reasons for doing so are posted on the Commission’s website.</p>
        <p>As I understand it, Mr. Alderson, after discussions with Senior Commission Counsel, has elected to withdraw his application for participant status, being satisfied that if he is called as a witness, he will be able to contribute to the work of the Commission to the extent he wishes.</p>
        <p>Before considering the remaining three applications, it seems appropriate to provide a brief overview of the nature and scope of our mandate and to say something about the Commission itself, which will help to give some context to these applications.</p>
        <p>As I noted in the Introductory Statement posted on the Commission’s website, there appears to be a consensus among law enforcement officials, academics and subject matter experts that British Columbia is a jurisdiction in which money laundering is flourishing.</p>
        <p>The mandate of the Commission—which was established by the Provincial Government—is very broad. It encompasses various economic sectors where money laundering is said to have taken root, grown and evolved, and it requires the Commission to make findings of fact in relation to:</p>
        <ul>
            <li>The extent, growth, evolution and methods of money laundering in British Columbia, with regard to specific economic sectors;</li>
            <li>The acts or omissions of responsible regulatory agencies and individuals, and whether those have contributed to money laundering in the province or amount to corruption;</li>
            <li>The scope and effectiveness of the anti-money laundering powers, duties and functions of these regulatory agencies and individuals; and</li>
            <li>The barriers to effective law enforcement in relation to money laundering.</li>
        </ul>
        <p>In addition, the Commission has a responsibility to make recommendations to address the conditions that have enabled money laundering to grow and evolve in the province.</p>
        <p>In recent years, there has been extensive media investigation and coverage of money laundering. There have also been studies and reports prepared by academics and other experts that shed light on the prevalence of money laundering in the province and on its noticeable effects.</p>
        <p>As a result, the public has become aware of, and concerned about, this problem. One recent poll reported that approximately 90% of British Columbians are concerned about money laundering.</p>
        <p>It is part of this Inquiry’s role to add to the public’s understanding of the nature and scale of money laundering in the province and to address its concerns, to the extent possible, through recommendations for action.</p>
        <p>There is also an incidental benefit from simply bringing additional concentrated attention to the crime of money laundering. The more awareness there is of its presence, and of the profound social harms it springs from and propagates, the less complacency there can be for facilitating or tolerating it.</p>
        <p>Brock Martland, Q.C. and Patrick McGowan, who are present at this hearing, are the two Senior Commission Counsel. They have undertaken the significant responsibility of assembling and organizing the evidence that will be placed before the Commission at the hearing stage. The evidence will come from many sources and will cover a broad array of topics. To assist in this task, they have put together a very capable team of lawyers and consultants. Biographies of all of the Commission Counsel are posted on our website.</p>
        <p>This Commission, like all commissions appointed under the <em>Public Inquiry Act, </em>S.B.C. 2007, c. 9, is independent of government. We serve the people of British Columbia.</p>
        <p>This means that the Commission must live up to certain standards in conducting its public hearings. One of the integral standards is that of fairness to those whose privacy interests, legal interests, or reputational interests may be affected by the proceedings. Another important standard for the Commission is thoroughness. The Commission must do its utmost to ensure that its subject matter is comprehensively and meaningfully covered. That entails hearing from a range of voices and points of view.</p>
        <p>One of the mechanisms of ensuring fairness and thoroughness is permitting certain parties to act as participants in the proceedings—if their interests may be affected by the findings of the Commission, if their participation would further the conduct of the Inquiry, and/or if their participation would contribute to the fairness of the Inquiry.</p>
        <p>Not all persons or organization representatives, who may be called as witnesses, are entitled to participant status. If a person believes that he or she has relevant evidence to give, they may be entitled to testify and they may be represented by counsel. It does not follow that having relevant evidence to give justifies a granting of participant status. The other conditions I have mentioned must be in play.</p>
        <p>This hearing is not adversarial. It is an attempt by all present to get at the root of the question of whether Messrs. Desmarais, Lightbody and Pinnock meet the criteria for status as participants, or whether their involvement is appropriately confined to be a witness or potential witness. I do not anticipate any need for extensive evidence or any cross-examination at this hearing. A simple exploration of the factual and statutory conditions at issue will lead to an appropriate resolution.</p>
        <p>As I understand it, Mr. Martland and Mr. McGowan have spoken with counsel for Messrs. Desmarais, Lightbody and Pinnock and have agreed upon a format for proceeding this morning. I will now ask one of them to set forth what format these proceedings will follow.</p>
    </div>
    <div class="ExpandableSectionTitleContainer" id="ExpandableSection01">
        <p class="ExpandableSectionTitle">Introductory Statement</p>
        <p class="ExpandableSectionUnderTitleLeft"></p>
        <p class="ExpandableSectionUnderTitleRight">July, 2019</p>
    </div>
    <div class="ExpandableSection" id="ExpandableSectionContent01">
        <h2>Commission of Inquiry into Money Laundering in British Columbia Introductory Statement from Commissioner Cullen</h2>
        <p>As has been reported, British Columbia is seen as a jurisdiction in which money laundering is flourishing. There appears to be a consensus among law enforcement officials, academics and subject matter experts that this perception is rooted in reality. It is important to note that because of its secretive nature, money laundering activities do not leave behind much clear evidence of their existence, nor do they generally produce witnesses who are motivated to publicly speak about it. Nevertheless, it is a situation that many British Columbians are concerned about.</p>
        <p>The Provincial Government has commissioned four recent reports dealing with money laundering in B.C.:</p>
        <ul>
            <li><em>Dirty Money: An Independent Review of Money Laundering in Lower Mainland Casinos Conducted for the Attorney General of British Columbia</em> <a href="https://news.gov.bc.ca/files/Gaming_Final_Report.pdf" target="_blank">https://news.gov.bc.ca/files/Gaming_Final_Report.pdf</a> Peter M. German, Q.C., March 31, 2018;</li>
            <li><em>Dirty Money – Part 2: Turning the Tide – An Independent Review of Money Laundering in B.C. Real Estate, Luxury Vehicle Sales & Horse Racing</em> <a href="https://news.gov.bc.ca/files/Dirty_Money_Report_Part_2.pdf" target="_blank">https://news.gov.bc.ca/files/Dirty_Money_Report_Part_2.pdf</a> Peter M. German, Q.C., March 31, 2019;</li>
            <li><em>Real Estate Regulatory Structure Review</em> <a href="https://news.gov.bc.ca/files/Real_Estate_Regulatory_Structure_Review_Report_2018.pdf" target="_blank">https://news.gov.bc.ca/files/Real_Estate_Regulatory_Structure_Review_Report_2018.pdf</a> Dan Perrin, 2018; and</li>
            <li><em>Combatting Money Laundering in BC Real Estate</em> <a href="https://news.gov.bc.ca/files/Combatting_Money_Laundering_Report.pdf" target="_blank">https://news.gov.bc.ca/files/Combatting_Money_Laundering_Report.pdf</a> Maureen Maloney, Tsur Somerville and Brigitte Unger, March 31, 2019.</li>
        </ul>
        <p>On May 15, 2019, in the wake of these reports, British Columbia Premier John Horgan announced the establishment of this Commission of Inquiry into Money Laundering in the province.</p>
        <p>The mandate of the Commission is broad. Its <a href="/tor/">terms of reference</a> require the Commission to make findings of fact with respect to:</p>
        <ul>
            <li>the extent, growth, evolution and methods of money laundering in British Columbia, with regard to specific economic sectors;</li>
            <li>the acts or omissions of responsible regulatory agencies and individuals, and whether those have contributed to money laundering in the province or amount to corruption;</li>
            <li>the scope and effectiveness of the anti-money laundering powers, duties and functions of these regulatory agencies and individuals; and</li>
            <li>the barriers to effective law enforcement in relation to money laundering.</li>
        </ul>
        <p>In addition, this Commission has the responsibility to make recommendations to address the conditions which have enabled money laundering to flourish.</p>
        <p>Within the Commission’s mandate is the review and consideration of the four reports on money laundering recently received by the Province. Those reports paint a worrisome picture of the state of affairs in the various economic sectors where money laundering is said to be an issue. They mirror the significant concern with which British Columbians view money laundering in their communities, and the extent to which issues of institutional effectiveness (or even integrity) in combatting it are at stake.</p>
        <p>Although much work has already been done, this Inquiry represents an opportunity to further shine a light on the issues. The Commission has various statutory powers available to it, such as the power to compel witnesses and order disclosure – powers that were not available to the authors of the previous reports. It is expected that this will enable a more comprehensive review of the nature and scope of money laundering in the province and the conditions that have permitted it to expand and evolve.</p>
        <p>Although this Commission has been created by an Order of government, and will be funded by the Provincial Government, it is an independent body that owes its allegiance solely to the people of British Columbia. In discharging its mandate, the Commission must fulfill its terms of reference in a manner that is financially accountable, while also having regard for certain touchstones common to public inquiries.</p>
        <p>First, the Inquiry must be effective and proceed with reasonable promptness; it must proceed in a timely way, although not at the expense of being thorough.</p>
        <p>Second, the Commission must be fair. Many of the individuals and agencies who will be engaged in the Commission’s work are involved because they have useful information, experience and insights to convey, not because they have something to answer for. The Commission must be strongly committed to ensuring that it respects the right of those individuals and agencies to have their privacy interests, legal interests and reputations protected.</p>
        <p>Third, the Commission must be thorough. Being thorough does not mean that every line of inquiry that could be followed must be followed. Rather, it means that the lines of inquiry that will be followed are those that meaningfully contribute to an understanding of the issues within the Commission’s mandate. To do less would undermine public confidence in the outcome of the Inquiry; to do more would sacrifice coherence and expedience, and foster an endless proceeding.</p>
        <p>Finally, the Commission must be open and transparent. This is crucial to the success of this important endeavour. Whatever findings of fact the Commission makes and whatever recommendations are proposed must rest on the premise that the public, for whom the Commission has been called, has had the opportunity to know and understand the factual and policy issues at play and to form its own opinion of the value and efficacy of the process and the outcome.</p>
        <p>The Commission will, in due course, publish rules of procedure that will ensure that the proceedings follow an orderly process, reflecting the sometimes competing imperatives of expeditiousness, fairness, thoroughness and openness. The Commission has included in the website its Rules for Standing and Participation, which will permit those persons and agencies seeking to participate in the Inquiry to apply to do so. You can read the <a href="/rules-for-standing/">Rules for Standing and Participation here</a>.</p>
        <p>Public inquiries are not only about providing information to the people of the province. British Columbians also benefit significantly from receiving information from interested members of the public. The Commission’s website, while still under development, provides contact information for any members of the public who wish to provide information or submissions. As the Commission’s work progresses, there will be more information shared on the website about how the public can be involved in the Inquiry.</p>
        <p>While the Commission is not yet fully staffed, several key roles have been filled. Biographies of these individuals are available on the website.</p>
        <p>The Commission will have both study and hearing components. The study component has already commenced; it includes an analysis of the four reports commissioned by the Province. It will also encompass a thorough examination of legislation, research and commentary with respect to money laundering and anti-money laundering processes, both in this and other jurisdictions, as well as consultation with individuals knowledgeable about these subjects. If necessary, original research may be commissioned to further advance the Commission’s understanding of issues within its terms of reference.</p>
        <p>At the same time as the study component of the Commission is underway, Inquiry staff will also be seeking the production of pertinent documents from regulatory, enforcement and other agencies relevant to the growth and evolution of money laundering in British Columbia. Based in part on their review of these documents and on what is learned during the study portion, Inquiry staff will conduct investigations and interview those whose evidence is likely to assist in understanding the various issues on which the Commission is required to report. This information will help to chart the course of the hearings which will contribute to a comprehensive understanding of the genesis, nature and extent of money laundering in British Columbia and the proposed solutions that will best address it.</p>
        <p>The scope of the Commission’s mandate is both broad and deep. The cooperation of all levels of government, public and private agencies, and individual citizens is critical to a successful outcome. The Commission looks forward to engaging with all of those who can help it come to grips with what is rightly regarded as a serious issue that casts a large shadow over British Columbia’s economic and institutional landscape.</p>
        <p>I am honoured to lead this effort as Commissioner and am proud of the experienced, knowledgeable team that we are building. My commitment is that my – and all members of the Commission’s staff – allegiance is to the people of British Columbia: to finding the facts and providing this information to you.</p>
        <p>The Honourable Austin Cullen, Commissioner</p>
        <p>Commission of Inquiry into Money Laundering in British Columbia</p>
    </div>
</div>
<script>
    $(document).ready(function() {
        let time = 250;
        $('#ExpandableSection01').click(function() {
            $('#ExpandableSectionContent01').slideToggle(time);
        });
        $('#ExpandableSection02').click(function() {
            $('#ExpandableSectionContent02').slideToggle(time);
        });
        $('#ExpandableSection03').click(function() {
            $('#ExpandableSectionContent03').slideToggle(time);
        });
        $('#ExpandableSection04').click(function() {
            $('#ExpandableSectionContent04').slideToggle(time);
        });
    });
</script>

<?php
include($_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php');
?>