<?php
$title = 'Introductory Statement';
include($_SERVER['DOCUMENT_ROOT'] . '/includes/head.php');
include($_SERVER['DOCUMENT_ROOT'] . '/includes/header.php');
include($_SERVER['DOCUMENT_ROOT'] . '/includes/navbar.php');
?>
<h1>Introductory Statement</h1>
<h2 style="text-align: center">Commission of Inquiry into<br>Money Laundering in British Columbia<br>Introductory Statement from Commissioner Cullen</h2>
<p>As has been reported, British Columbia is seen as a jurisdiction in which money laundering is flourishing. There appears to be a consensus among law enforcement officials, academics and subject matter experts that this perception is rooted in reality. It is important to note that because of its secretive nature, money laundering activities do not leave behind much clear evidence of their existence, nor do they generally produce witnesses who are motivated to publicly speak about it. Nevertheless, it is a situation that many British Columbians are concerned about.</p>
<p>The Provincial Government has commissioned four recent reports dealing with money laundering in B.C.:</p>
<ul>
    <ol><em>Dirty Money: An Independent Review of Money Laundering in Lower Mainland Casinos Conducted for the Attorney General of British Columbia</em> <a href="https://news.gov.bc.ca/files/Gaming_Final_Report.pdf" target="_blank">https://news.gov.bc.ca/files/Gaming Final Report.pdf</a> Peter M. German, Q.C., March 31, 2018;</ol>
    <ol><em>Dirty Money – Part 2: Turning the Tide – An Independent Review of Money Laundering in B.C. Real Estate, Luxury Vehicle Sales & Horse Racing</em> <a href="https://news.gov.bc.ca/files/Dirty_Money_Report_Part_2.pdf" target="_blank">https://news.gov.bc.ca/files/Dirty Money Report Part 2.pdf</a> Peter M. German, Q.C., March 31, 2019;</ol>
    <ol><em>Real Estate Regulatory Structure Review</em> <a href="https://news.gov.bc.ca/files/Real_Estate_Regulatory_Structure_Review_Report_2018.pdf" target="_blank">https://news.gov.bc.ca/files/Real Estate Regulatory Structure Review Report 2018.pdf</a> Dan Perrin, 2018; and</ol>
    <ol><em>Combatting Money Laundering in BC Real Estate</em> <a href="https://news.gov.bc.ca/files/Combatting_Money_Laundering_Report.pdf" target="_blank">https://news.gov.bc.ca/files/Combatting Money Laundering Report.pdf</a> Maureen Maloney, Tsur Somerville and Brigitte Unger, March 31, 2019.</ol>
</ul>
<p>On May 15, 2019, in the wake of these reports, British Columbia Premier John Horgan announced the establishment of this Commission of Inquiry into Money Laundering in the province.</p>
<p>The mandate of the Commission is broad. Its <a href="/tor/">terms of reference</a> require the Commission to make findings of fact with respect to:</p>
<ul>
    <ol>the extent, growth, evolution and methods of money laundering in British Columbia, with regard to specific economic sectors;</ol>
    <ol>the acts or omissions of responsible regulatory agencies and individuals, and whether those have contributed to money laundering in the province or amount to corruption;</ol>
    <ol>the scope and effectiveness of the anti-money laundering powers, duties and functions of these regulatory agencies and individuals; and</ol>
    <ol>the barriers to effective law enforcement in relation to money laundering.</ol>
</ul>
<p>In addition, this Commission has the responsibility to make recommendations to address the conditions which have enabled money laundering to flourish.</p>
<p>Within the Commission’s mandate is the review and consideration of the four reports on money laundering recently received by the Province. Those reports paint a worrisome picture of the state of affairs in the various economic sectors where money laundering is said to be an issue. They mirror the significant concern with which British Columbians view money laundering in their communities, and the extent to which issues of institutional effectiveness (or even integrity) in combatting it are at stake.</p>
<p>Although much work has already been done, this Inquiry represents an opportunity to further shine a light on the issues. The Commission has various statutory powers available to it, such as the power to compel witnesses and order disclosure – powers that were not available to the authors of the previous reports. It is expected that this will enable a more comprehensive review of the nature and scope of money laundering in the province and the conditions that have permitted it to expand and evolve.</p>
<p>Although this Commission has been created by an Order of government, and will be funded by the Provincial Government, it is an independent body that owes its allegiance solely to the people of British Columbia. In discharging its mandate, the Commission must fulfill its terms of reference in a manner that is financially accountable, while also having regard for certain touchstones common to public inquiries.</p>
<p>First, the Inquiry must be effective and proceed with reasonable promptness; it must proceed in a timely way, although not at the expense of being thorough.</p>
<p>Second, the Commission must be fair. Many of the individuals and agencies who will be engaged in the Commission’s work are involved because they have useful information, experience and insights to convey, not because they have something to answer for. The Commission must be strongly committed to ensuring that it respects the right of those individuals and agencies to have their privacy interests, legal interests and reputations protected.</p>
<p>Third, the Commission must be thorough. Being thorough does not mean that every line of inquiry that could be followed must be followed. Rather, it means that the lines of inquiry that will be followed are those that meaningfully contribute to an understanding of the issues within the Commission’s mandate. To do less would undermine public confidence in the outcome of the Inquiry; to do more would sacrifice coherence and expedience, and foster an endless proceeding.</p>
<p>Finally, the Commission must be open and transparent. This is crucial to the success of this important endeavour. Whatever findings of fact the Commission makes and whatever recommendations are proposed must rest on the premise that the public, for whom the Commission has been called, has had the opportunity to know and understand the factual and policy issues at play and to form its own opinion of the value and efficacy of the process and the outcome.</p>
<p>The Commission will, in due course, publish rules of procedure that will ensure that the proceedings follow an orderly process, reflecting the sometimes competing imperatives of expeditiousness, fairness, thoroughness and openness. The Commission has included in the website its Rules for Standing and Participation, which will permit those persons and agencies seeking to participate in the Inquiry to apply to do so. You can read the <a href="/rules-for-standing/">Rules for Standing and Participation here</a>.</p>
<p>Public inquiries are not only about providing information to the people of the province. British Columbians also benefit significantly from receiving information from interested members of the public. The Commission’s website, while still under development, provides contact information for any members of the public who wish to provide information or submissions. As the Commission’s work progresses, there will be more information shared on the website about how the public can be involved in the Inquiry.</p>
<p>While the Commission is not yet fully staffed, several key roles have been filled. Biographies of these individuals are available on the website.</p>
<p>The Commission will have both study and hearing components. The study component has already commenced; it includes an analysis of the four reports commissioned by the Province. It will also encompass a thorough examination of legislation, research and commentary with respect to money laundering and anti-money laundering processes, both in this and other jurisdictions, as well as consultation with individuals knowledgeable about these subjects. If necessary, original research may be commissioned to further advance the Commission’s understanding of issues within its terms of reference.</p>
<p>At the same time as the study component of the Commission is underway, Inquiry staff will also be seeking the production of pertinent documents from regulatory, enforcement and other agencies relevant to the growth and evolution of money laundering in British Columbia. Based in part on their review of these documents and on what is learned during the study portion, Inquiry staff will conduct investigations and interview those whose evidence is likely to assist in understanding the various issues on which the Commission is required to report. This information will help to chart the course of the hearings which will contribute to a comprehensive understanding of the genesis, nature and extent of money laundering in British Columbia and the proposed solutions that will best address it.</p>
<p>The scope of the Commission’s mandate is both broad and deep. The cooperation of all levels of government, public and private agencies, and individual citizens is critical to a successful outcome. The Commission looks forward to engaging with all of those who can help it come to grips with what is rightly regarded as a serious issue that casts a large shadow over British Columbia’s economic and institutional landscape.</p>
<p>I am honoured to lead this effort as Commissioner and am proud of the experienced, knowledgeable team that we are building. My commitment is that my – and all members of the Commission’s staff – allegiance is to the people of British Columbia: to finding the facts and providing this information to you.</p>
<p>The Honourable Austin Cullen, Commissioner</p>
<p>Commission of Inquiry into Money Laundering in British Columbia</p>
<?php
include($_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php');
?>